services:
  configurator:
    environment:
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
    depends_on:
      - redis-cache
      - redis-queue
      - redis-socketio

  redis-cache:
    image: redis:6.2-alpine
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:6.2-alpine
    volumes:
      - redis-queue-data:/data

  redis-socketio:
    image: redis:6.2-alpine
    volumes:
      - redis-socketio-data:/data

volumes:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data:
