sudo: required

dist: xenial

services:
  - docker

before_install:
  - if [[ "$BUILD" != "development" ]]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    sudo apt-get update && sudo apt-get -y install git;
    fi
  - if [[ $BUILD == "development" ]];then
    sudo apt-get update && sudo apt-get -y install docker-compose;
    fi
  - chmod u+x ./travis.sh

after_success:
  - docker --version

matrix:
  include:
    - name: "Build Frappe python environment (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.sh --worker --service frappe --tag edge 
        - ./travis.sh --worker --service frappe --tag develop --tag-only
    - name: "Build Frappe nginx + static assets (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.sh --assets --service frappe --tag edge
        - ./travis.sh --assets --service frappe --tag develop--tag-only
    - name: "Build ERPNext python environment (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.sh --worker --service erpnext --tag edge
        - ./travis.sh --worker --service erpnext --tag develop --tag-only
    - name: "Build ERPNext nginx + static assets (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.sh --assets --service erpnext --tag edge 
        - ./travis.sh --assets --service erpnext --tag develop --tag-only
    - name: "Build Frappe socketio service (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.sh --socketio --service frappe --tag edge
        - ./travis.sh --socketio --service frappe --tag develop --tag-only
    - name: "Build Frappe python environment (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --worker --service frappe --git-branch 12 
        - ./travis.sh --worker --service frappe --tag v12 --tag-only
        - ./travis.sh --worker --service frappe --tag version-12 --tag-only
    - name: "Build Frappe nginx + static assets (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --assets --service frappe --git-branch 12 
        - ./travis.sh --assets --service frappe --tag v12 --tag-only
        - ./travis.sh --assets --service frappe --tag version-12 --tag-only
    - name: "Build ERPNext python environment (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --worker --service erpnext --git-branch 12
        - ./travis.sh --worker --service erpnext --tag v12 --tag-only
        - ./travis.sh --worker --service erpnext --tag version-12 --tag-only
    - name: "Build ERPNext nginx + static assets (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --assets --service erpnext--git-branch 12
        - ./travis.sh --assets --service erpnext --tag v12 --tag-only
        - ./travis.sh --assets --service erpnext --tag version-12 --tag-only
    - name: "Build Frappe socketio service (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --socketio --service frappe --git-branch 11
        - ./travis.sh --socketio --service frappe --tag v11 --tag-only
        - ./travis.sh --socketio --service frappe --tag version-11 --tag-only
    - name: "Build Frappe python environment (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --worker --service frappe --git-branch 11 
        - ./travis.sh --worker --service frappe --tag v11 --tag-only
        - ./travis.sh --worker --service frappe --tag version-11 --tag-only
    - name: "Build Frappe nginx + static assets (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --assets --service frappe --git-branch 11 
        - ./travis.sh --assets --service frappe --tag v11 --tag-only
        - ./travis.sh --assets --service frappe --tag version-11 --tag-only
    - name: "Build ERPNext python environment (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --worker --service erpnext --git-branch 11
        - ./travis.sh --worker --service erpnext --tag v11 --tag-only
        - ./travis.sh --worker --service erpnext --tag version-11 --tag-only
    - name: "Build ERPNext nginx + static assets (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --assets --service erpnext--git-branch 11
        - ./travis.sh --assets --service erpnext --tag v11 --tag-only
        - ./travis.sh --assets --service erpnext --tag version-11 --tag-only
    - name: "Build Frappe socketio service (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --socketio --service frappe --git-branch 11
        - ./travis.sh --socketio --service frappe --tag v11 --tag-only
        - ./travis.sh --socketio --service frappe --tag version-11 --tag-only
        
    