sudo: required

dist: xenial

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ $BUILD == "development" ];then
      sudo apt-get update;
      sudo apt-get -y install docker-compose;
    fi

install:
  - if [ $BUILD == "development" ];then
      chmod ugo+x ./dbench;
      chmod ugo+x ./test.sh;
      ./dbench setup docker;
      ./dbench init frappe-bench;
      ./dbench new-site site1.local;
      ./dbench setup hosts;
    fi

after_success:
  - docker --version

matrix:
  include:
    - name: "Test frappe / erpnext development"
      env: BUILD=development
      script:
        - ./test.sh
        - ./dbench setup docker stop
    - name: "Build frappe / erpnext python environment"
      script:
        - docker build -t erpnext-python build/erpnext-python
        - docker tag erpnext-python frappe/erpnext-python:edge
        - docker push frappe/erpnext-python:edge
    - name: "Build frappe / erpnext nginx + static assets"
      script:
        - docker build -t erpnext-assets build/erpnext-assets
        - docker tag erpnext-assets frappe/erpnext-assets:edge
        - docker push frappe/erpnext-assets:edge
    - name: "Build frappe socketio service"
      script:
        - docker build -t frappe-socketio build/frappe-socketio
        - docker tag frappe-socketio frappe/frappe-socketio:edge
        - docker push frappe/frappe-socketio:edge
