sudo: required

dist: xenial

services:
  - docker

before_install:
  - if [[ "$BUILD" != "development" ]]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    sudo apt-get update && sudo apt-get -y install git;
    fi
  - if [[ $BUILD == "development" ]];then
    sudo apt-get update && sudo apt-get -y install docker-compose;
    fi
  - chmod u+x ./travis.sh

after_success:
  - docker --version

matrix:
  include:
    - name: "Build Frappe python environment (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.sh --worker --tag edge --name frappe
        - ./travis.sh --worker --tag develop --name frappe --tag-only
    - name: "Build Frappe nginx + static assets (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.sh --assets --tag edge --name frappe
        - ./travis.sh --assets --tag develop --name frappe --tag-only
    - name: "Build ERPNext python environment (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.sh --worker --tag edge --name erpnext
        - ./travis.sh --worker --tag develop --name erpnext --tag-only
    - name: "Build ERPNext nginx + static assets (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.sh --assets --tag edge --name erpnext
        - ./travis.sh --assets --tag develop --name erpnext --tag-only
    - name: "Build Frappe socketio service (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.sh --socketio --tag edge --name frappe
        - ./travis.sh --socketio --tag develop --name frappe --tag-only
    - name: "Build Frappe python environment (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --worker --git-branch 12 --name frappe 
        - ./travis.sh --worker --tag v12 --name frappe --tag-only
        - ./travis.sh --worker --tag version-12 --name frappe --tag-only
    - name: "Build Frappe nginx + static assets (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --assets --git-branch 12 --name frappe 
        - ./travis.sh --assets --tag v12 --name frappe --tag-only
        - ./travis.sh --assets --tag version-12 --name frappe --tag-only
    - name: "Build ERPNext python environment (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --worker --git-branch 12 --name erpnext
        - ./travis.sh --worker --tag v12 --name erpnext --tag-only
        - ./travis.sh --worker --tag version-12 --name erpnext --tag-only
    - name: "Build ERPNext nginx + static assets (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --assets --git-branch 12 --name erpnext
        - ./travis.sh --assets --tag v12 --name erpnext --tag-only
        - ./travis.sh --assets --tag version-12 --name erpnext --tag-only
    - name: "Build Frappe socketio service (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --socketio --git-branch 12 --name frappe
        - ./travis.sh --socketio --tag v12 --name frappe --tag-only
        - ./travis.sh --socketio --tag version-12 --name frappe --tag-only
    - name: "Build Frappe python environment (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --worker --git-branch 11 --name frappe
        - ./travis.sh --worker --tag v11 --name frappe --tag-only
        - ./travis.sh --worker --tag version-11 --name frappe --tag-only
    - name: "Build Frappe nginx + static assets (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --assets --git-branch 11 --name frappe
        - ./travis.sh --assets --tag v11 --name frappe --tag-only
        - ./travis.sh --assets --tag version-11 --name frappe --tag-only
    - name: "Build ERPNext python environment (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --worker --git-branch 11 --name erpnext
        - ./travis.sh --worker --tag v11 --name erpnext --tag-only
        - ./travis.sh --worker --tag version-11 --name erpnext --tag-only
    - name: "Build ERPNext nginx + static assets (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --assets --git-branch 11 --name erpnext
        - ./travis.sh --assets --tag v11 --name erpnext --tag-only
        - ./travis.sh --assets --tag version-11 --name erpnext --tag-only
    - name: "Build Frappe socketio service (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.sh --socketio --git-branch 11 --name erpnext
        - ./travis.sh --socketio --tag v11 --name erpnext --tag-only
        - ./travis.sh --socketio --tag version-11 --name erpnext --tag-only
