sudo: required

dist: xenial

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ $BUILD == "development" ];then
      sudo apt-get update;
      sudo apt-get -y install docker-compose;
    fi

install:
  - if [ $BUILD == "development" ];then
      chmod ugo+x ./dbench;
      chmod ugo+x ./test.sh;
      ./dbench setup docker;
      ./dbench init frappe-bench;
      ./dbench new-site site1.local;
      ./dbench setup hosts;
    fi

after_success:
  - docker --version

matrix:
  include:
    - name: "Test Frappe / ERPNext development"
      env: BUILD=development
      script:
        - ./test.sh
        - ./dbench setup docker stop
    - name: "Build Frappe python environment"
      script:
        - docker build -t frappe-worker -f build/frappe-worker/Dockerfile .
        - docker tag frappe-worker frappe/frappe-worker:edge
        - docker push frappe/frappe-worker:edge
    - name: "Build Frappe nginx + static assets"
      script:
        - docker build -t frappe-assets -f build/frappe-assets/Dockerfile .
        - docker tag frappe-assets frappe/frappe-assets:edge
        - docker push frappe/frappe-assets:edge
    - name: "Build ERPNext python environment"
      script:
        - docker build -t erpnext-worker -f build/erpnext-worker/Dockerfile .
        - docker tag erpnext-worker frappe/erpnext-worker:edge
        - docker push frappe/erpnext-worker:edge
    - name: "Build ERPNext nginx + static assets"
      script:
        - docker build -t erpnext-assets -f build/erpnext-assets/Dockerfile .
        - docker tag erpnext-assets frappe/erpnext-assets:edge
        - docker push frappe/erpnext-assets:edge
    - name: "Build Frappe socketio service"
      script:
        - docker build -t frappe-socketio -f build/frappe-socketio/Dockerfile .
        - docker tag frappe-socketio frappe/frappe-socketio:edge
        - docker push frappe/frappe-socketio:edge
