sudo: required

dist: xenial

services:
  - docker

before_install:
  - if [[ "$BUILD" != "development" ]]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    sudo apt-get update && sudo apt-get -y install git;
    fi
  - if [[ $BUILD == "development" ]];then
    sudo apt-get update && sudo apt-get -y install docker-compose;
    fi

after_success:
  - docker --version

jobs:
  include:
    - stage: "Build Frappe python environment (edge)"
      if: branch = develop AND type != pull_request
      script:
        - docker build -t frappe-worker -f build/frappe-worker/Dockerfile .
        - docker tag frappe-worker frappe/frappe-worker:edge
        - docker tag frappe-worker frappe/frappe-worker:develop
        - docker push frappe/frappe-worker:edge
        - docker push frappe/frappe-worker:develop
    - stage: "Build Frappe nginx + static assets (edge)"
      if: branch = develop AND type != pull_request
      script:
        - docker build -t frappe-assets -f build/frappe-assets/Dockerfile .
        - docker tag frappe-assets frappe/frappe-assets:edge
        - docker tag frappe-assets frappe/frappe-assets:develop
        - docker push frappe/frappe-assets:edge
        - docker push frappe/frappe-assets:develop
    - stage: "Build ERPNext python environment (edge)"
      if: branch = develop AND type != pull_request
      script:
        - docker build -t erpnext-worker -f build/erpnext-worker/Dockerfile .
        - docker tag erpnext-worker frappe/erpnext-worker:edge
        - docker tag erpnext-worker frappe/erpnext-worker:develop
        - docker push frappe/erpnext-worker:edge
        - docker push frappe/erpnext-worker:develop
    - stage: "Build ERPNext nginx + static assets (edge)"
      if: branch = develop AND type != pull_request
      script:
        - docker build -t erpnext-assets -f build/erpnext-assets/Dockerfile .
        - docker tag erpnext-assets frappe/erpnext-assets:edge
        - docker tag erpnext-assets frappe/erpnext-assets:develop
        - docker push frappe/erpnext-assets:edge
        - docker push frappe/erpnext-assets:develop
    - stage: "Build Frappe socketio service (edge)"
      if: branch = develop AND type != pull_request
      script:
        - docker build -t frappe-socketio -f build/frappe-socketio/Dockerfile .
        - docker tag frappe-socketio frappe/frappe-socketio:edge
        - docker tag frappe-socketio frappe/frappe-socketio:develop
        - docker push frappe/frappe-socketio:edge
        - docker push frappe/frappe-socketio:develop
    - stage: "Build Frappe python environment (v12)"
      if: branch = master AND type != pull_request
      script:
        - git clone https://github.com/frappe/frappe --branch version-12
        - cd frappe
        - git fetch --tags
        - export VERSION=$(git tag --list --sort=-version:refname "v12*" | sed -n 1p | sed -e 's#.*@\(\)#\1#')
        - cd ..
        - docker build -t frappe/frappe-worker:$VERSION -f build/frappe-worker/v12.Dockerfile .
        - docker tag frappe/frappe-worker:$VERSION frappe/frappe-worker:version-12
        - docker tag frappe/frappe-worker:$VERSION frappe/frappe-worker:v12
        - docker push frappe/frappe-worker:$VERSION
        - docker push frappe/frappe-worker:version-12
        - docker push frappe/frappe-worker:v12
    - stage: "Build Frappe nginx + static assets (v12)"
      if: branch = master AND type != pull_request
      script:
        - git clone https://github.com/frappe/frappe --branch version-12
        - cd frappe
        - git fetch --tags
        - export VERSION=$(git tag --list --sort=-version:refname "v12*" | sed -n 1p | sed -e 's#.*@\(\)#\1#')
        - cd ..
        - docker build -t frappe/frappe-assets:$VERSION -f build/frappe-assets/v12.Dockerfile .
        - docker tag frappe/frappe-assets:$VERSION frappe/frappe-assets:version-12
        - docker tag frappe/frappe-assets:$VERSION frappe/frappe-assets:v12
        - docker push frappe/frappe-assets:$VERSION
        - docker push frappe/frappe-assets:version-12
        - docker push frappe/frappe-assets:v12
    - stage: "Build ERPNext python environment (v12)"
      if: branch = master AND type != pull_request
      script:
        - git clone https://github.com/frappe/erpnext --branch version-12
        - cd erpnext
        - git fetch --tags
        - export VERSION=$(git tag --list --sort=-version:refname "v12*" | sed -n 1p | sed -e 's#.*@\(\)#\1#')
        - cd ..
        - docker build -t frappe/erpnext-worker:$VERSION -f build/erpnext-worker/v12.Dockerfile .
        - docker tag frappe/erpnext-worker:$VERSION frappe/erpnext-worker:version-12
        - docker tag frappe/erpnext-worker:$VERSION frappe/erpnext-worker:v12
        - docker push frappe/erpnext-worker:$VERSION
        - docker push frappe/erpnext-worker:version-12
        - docker push frappe/erpnext-worker:v12
    - stage: "Build ERPNext nginx + static assets (v12)"
      if: branch = master AND type != pull_request
      script:
        - git clone https://github.com/frappe/erpnext --branch version-12
        - cd erpnext
        - git fetch --tags
        - export VERSION=$(git tag --list --sort=-version:refname "v12*" | sed -n 1p | sed -e 's#.*@\(\)#\1#')
        - cd ..
        - docker build -t frappe/erpnext-assets:$VERSION -f build/erpnext-assets/v12.Dockerfile .
        - docker tag frappe/erpnext-assets:$VERSION frappe/erpnext-assets:version-12
        - docker tag frappe/erpnext-assets:$VERSION frappe/erpnext-assets:v12
        - docker push frappe/erpnext-assets:$VERSION
        - docker push frappe/erpnext-assets:version-12
        - docker push frappe/erpnext-assets:v12
    - stage: "Build Frappe socketio service (v12)"
      if: branch = master AND type != pull_request
      script:
        - git clone https://github.com/frappe/frappe --branch version-12
        - cd frappe
        - git fetch --tags
        - export VERSION=$(git tag --list --sort=-version:refname "v12*" | sed -n 1p | sed -e 's#.*@\(\)#\1#')
        - cd ..
        - docker build -t frappe/frappe-socketio:$VERSION -f build/frappe-socketio/v12.Dockerfile .
        - docker tag frappe/frappe-socketio:$VERSION frappe/frappe-socketio:version-12
        - docker tag frappe/frappe-socketio:$VERSION frappe/frappe-socketio:v12
        - docker push frappe/frappe-socketio:$VERSION
        - docker push frappe/frappe-socketio:version-12
        - docker push frappe/frappe-socketio:v12
    - stage: "Build Frappe python environment (v11)"
      if: branch = master AND type != pull_request
      script:
        - git clone https://github.com/frappe/frappe --branch version-11
        - cd frappe
        - git fetch --tags
        - export VERSION=$(git tag --list --sort=-version:refname "v11*" | sed -n 1p | sed -e 's#.*@\(\)#\1#')
        - cd ..
        - docker build -t frappe/frappe-worker:$VERSION -f build/frappe-worker/v11.Dockerfile .
        - docker tag frappe/frappe-worker:$VERSION frappe/frappe-worker:version-11
        - docker tag frappe/frappe-worker:$VERSION frappe/frappe-worker:v11
        - docker push frappe/frappe-worker:$VERSION
        - docker push frappe/frappe-worker:version-11
        - docker push frappe/frappe-worker:v11
    - stage: "Build Frappe nginx + static assets (v11)"
      if: branch = master AND type != pull_request
      script:
        - git clone https://github.com/frappe/frappe --branch version-11
        - cd frappe
        - git fetch --tags
        - export VERSION=$(git tag --list --sort=-version:refname "v11*" | sed -n 1p | sed -e 's#.*@\(\)#\1#')
        - cd ..
        - docker build -t frappe/frappe-assets:$VERSION -f build/frappe-assets/v11.Dockerfile .
        - docker tag frappe/frappe-assets:$VERSION frappe/frappe-assets:version-11
        - docker tag frappe/frappe-assets:$VERSION frappe/frappe-assets:v11
        - docker push frappe/frappe-assets:$VERSION
        - docker push frappe/frappe-assets:version-11
        - docker push frappe/frappe-assets:v11
    - stage: "Build ERPNext python environment (v11)"
      if: branch = master AND type != pull_request
      script:
        - git clone https://github.com/frappe/erpnext --branch version-11
        - cd erpnext
        - git fetch --tags
        - export VERSION=$(git tag --list --sort=-version:refname "v11*" | sed -n 1p | sed -e 's#.*@\(\)#\1#')
        - cd ..
        - docker build -t frappe/erpnext-worker:$VERSION -f build/erpnext-worker/v11.Dockerfile .
        - docker tag frappe/erpnext-worker:$VERSION frappe/erpnext-worker:version-11
        - docker tag frappe/erpnext-worker:$VERSION frappe/erpnext-worker:v11
        - docker push frappe/erpnext-worker:$VERSION
        - docker push frappe/erpnext-worker:version-11
        - docker push frappe/erpnext-worker:v11
    - stage: "Build ERPNext nginx + static assets (v11)"
      if: branch = master AND type != pull_request
      script:
        - git clone https://github.com/frappe/erpnext --branch version-11
        - cd erpnext
        - git fetch --tags
        - export VERSION=$(git tag --list --sort=-version:refname "v11*" | sed -n 1p | sed -e 's#.*@\(\)#\1#')
        - cd ..
        - docker build -t frappe/erpnext-assets:$VERSION -f build/erpnext-assets/v11.Dockerfile .
        - docker tag frappe/erpnext-assets:$VERSION frappe/erpnext-assets:version-11
        - docker tag frappe/erpnext-assets:$VERSION frappe/erpnext-assets:v11
        - docker push frappe/erpnext-assets:$VERSION
        - docker push frappe/erpnext-assets:version-11
        - docker push frappe/erpnext-assets:v11
    - stage: "Build Frappe socketio service (v11)"
      if: branch = master AND type != pull_request
      script:
        - git clone https://github.com/frappe/frappe --branch version-11
        - cd frappe
        - git fetch --tags
        - export VERSION=$(git tag --list --sort=-version:refname "v11*" | sed -n 1p | sed -e 's#.*@\(\)#\1#')
        - cd ..
        - docker build -t frappe/frappe-socketio:$VERSION -f build/frappe-socketio/v11.Dockerfile .
        - docker tag frappe/frappe-socketio:$VERSION frappe/frappe-socketio:version-11
        - docker tag frappe/frappe-socketio:$VERSION frappe/frappe-socketio:v11
        - docker push frappe/frappe-socketio:$VERSION
        - docker push frappe/frappe-socketio:version-11
        - docker push frappe/frappe-socketio:v11
