sudo: required

dist: xenial

services:
  - docker

before_install:
  - if [[ "$BUILD" != "development" ]]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    sudo apt-get update && sudo apt-get -y install git;
    fi
  - if [[ $BUILD == "development" ]];then
    sudo apt-get update && sudo apt-get -y install docker-compose;
    fi
  - chmod u+x ./travis.py

after_success:
  - docker --version

jobs:
  include:
    - stage: "Build Frappe python environment (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.py frappe --worker --tag edge 
        - ./travis.py frappe --worker --tag develop --tag-only
    - stage: "Build Frappe nginx + static assets (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.py frappe --nginx --tag edge
        - ./travis.py frappe --nginx --tag develop--tag-only
    - stage: "Build ERPNext python environment (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.py erpnext --worker --tag edge
        - ./travis.py erpnext --worker --tag develop --tag-only
    - stage: "Build ERPNext nginx + static assets (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.py erpnext --nginx --tag edge 
        - ./travis.py erpnext --nginx --tag develop --tag-only
    - stage: "Build Frappe socketio service (edge)"
      if: branch = develop AND type != pull_request
      script:
        - ./travis.py frappe --socketio --tag edge
        - ./travis.py frappe --socketio --tag develop --tag-only
    - stage: "Build Frappe python environment (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py frappe --worker --git-branch 12 
        - ./travis.py frappe --worker --tag v12 --tag-only
        - ./travis.py frappe --worker --tag version-12 --tag-only
    - stage: "Build Frappe nginx + static assets (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py frappe --nginx --git-branch 12 
        - ./travis.py frappe --nginx --tag v12 --tag-only
        - ./travis.py frappe --nginx --tag version-12 --tag-only
    - stage: "Build ERPNext python environment (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py erpnext --worker --git-branch 12
        - ./travis.py erpnext --worker --tag v12 --tag-only
        - ./travis.py erpnext --worker --tag version-12 --tag-only
    - stage: "Build ERPNext nginx + static assets (v12)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py erpnext --nginx --git-branch 12
        - ./travis.py erpnext --nginx --tag v12 --tag-only
        - ./travis.py erpnext --nginx --tag version-12 --tag-only
    - stage: "Build Frappe socketio service (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py frappe --socketio --git-branch 11
        - ./travis.py frappe --socketio --tag v11 --tag-only
        - ./travis.py frappe --socketio --tag version-11 --tag-only
    - stage: "Build Frappe python environment (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py frappe --worker --git-branch 11 
        - ./travis.py frappe --worker --tag v11 --tag-only
        - ./travis.py frappe  --worker --tag version-11 --tag-only
    - stage: "Build Frappe nginx + static assets (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py erpnext frappe --nginx --git-branch 11 
        - ./travis.py erpnext frappe --nginx --tag v11 --tag-only
        - ./travis.py erpnext frappe --nginx --tag version-11 --tag-only
    - stage: "Build ERPNext python environment (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py erpnext --worker --git-branch 11
        - ./travis.py erpnext --worker --tag v11 --tag-only
        - ./travis.py erpnext --worker --tag version-11 --tag-only
    - stage: "Build ERPNext nginx + static assets (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py erpnext --nginx --git-branch 11
        - ./travis.py erpnext --nginx --tag v11 --tag-only
        - ./travis.py erpnext --nginx --tag version-11 --tag-only
    - stage: "Build Frappe socketio service (v11)"
      if: branch = master AND type != pull_request
      script:
        - ./travis.py frappe --socketio --git-branch 11
        - ./travis.py frappe --socketio --tag v11 --tag-only
        - ./travis.py frappe --socketio --tag version-11 --tag-only
        
    