name: Bench

on:
  pull_request:
    branches:
      - main
    paths:
      - build/bench/**
      - docker-bake.hcl

  schedule:
    # Every day at 12:00 pm
    - cron: 0 0 * * *

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test
        uses: docker/bake-action@v1.7.0
        with:
          files: docker-bake.hcl
          targets: bench-test

      - name: Login
        if: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        if: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
        uses: docker/bake-action@v1.7.0
        with:
          targets: bench
          files: docker-bake.hcl
          push: true
