name: Integration Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - .github/scripts/get-latest-tags.sh
      - build/**
      - installation/**
      - tests/**
      - .dockerignore
      - docker-bake.hcl
      - env-example

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - .github/scripts/get-latest-tags.sh
      - build/**
      - installation/**
      - tests/**
      - .dockerignore
      - docker-bake.hcl
      - env-example

  workflow_dispatch:

  schedule:
    # Every day at 01:00 am
    # Develop images are built at 12:00 pm, we want to use them
    # Also, we don't build new images on this event
    - cron: 0 1 * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest versions
        if: github.event_name != 'schedule'
        run: ./.github/scripts/get-latest-tags.sh
        env:
          VERSION: 13

      - name: Build
        if: github.event_name != 'schedule'
        uses: docker/bake-action@v1.7.0
        with:
          files: docker-bake.hcl
          targets: frappe-develop,frappe-stable
          load: true
        env:
          GIT_TAG: ${{ env.FRAPPE_VERSION }}

      - name: Test
        run: ./tests/integration-test.sh
